### ISSUE TITLE
Xuan Truong

### ISSUE THREAD

**Issue by Thanhha58** [Antimicrobial-stewardship-evaluation/DOT1000_hospital#1]
***Data sử dụng:** 
 + XT_Patient_Q1.Rds, ...Q2, ...Q3,.....Q4
 + XT_drug_in_Q1_2021.Rds....Q2,.....Q3, .....Q4             + XT_Drug_Out_Q1_2021.Rds,....Q2,....Q3,....Q4
 + XT_bed.Rds

***Cleaned tab:**
![image](https://user-images.githubusercontent.com/91650070/229263472-50446234-d86d-4915-81e8-b7e3b6055e93.png)

![image](https://user-images.githubusercontent.com/91650070/229263509-02e8a398-0bc5-475e-9518-d27ea468ce8b.png)

![image](https://user-images.githubusercontent.com/91650070/229263748-7007a610-5faf-4e6d-bed5-9d218ab6745f.png)

**- Lỗi các tab kết quả**

![image](https://user-images.githubusercontent.com/91650070/228543904-8b77122a-ee7c-4ae0-a387-b447ca8d0f7f.png)

**Comment by tungstrinh** [comment]
@Thanhha58 em chụp ảnh kết quả của cleaned data tab nào. Thế này anh khó hình dung lắm.

**Comment by tungstrinh** [comment]
Với cả cho anh biết em dùng file nào để reproducible được nhé.
